version: '3.8'

services:
  kasumi_frontend:
    restart: unless-stopped
    build:
      context: ./kasumi_frontend
    environment:
      - INTERNAL_API_URL=http://kasumi_backend:3000/api
      - PUBLIC_URL=https://kasumi.no
      - PUBLIC_VARIANT=original
      - PUBLIC_DEFAULT_LANG=no
      - PUBLIC_AVAILABLE_LANGS=["no", "en", "pt"]
      - ANALYTICS_SCRIPT=
      - NODE_ENV=production
    ports:
      - "8084:3000"
    depends_on:
      - kasumi_backend

  kasumi_backend:
    build: ./kasumi_backend
    ports:
      - "3000:3000"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data:
